import { type NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: users, fetchStatus, trpc } = api.user.getAll.useQuery();
  console.log(users, trpc.path);

  return (
    <>
      <Head>
        <title>PATA Builder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className=" min-h-screen w-full border-2 border-b-0 border-t-0 md:max-w-2xl">
          {fetchStatus}
        </div>
      </main>
    </>
  );
};

export default Home;
